# Railway configuration for WordRush backend service

[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"

[deploy.variables]
NODE_ENV = "production"
PORT = "5000"
