[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "wordrush-backend"
source = "server"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.variables]
NODE_ENV = "production"
PORT = "5000"

[[services]]
name = "wordrush-frontend" 
source = "client"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{wordrush-backend.RAILWAY_PUBLIC_DOMAIN}}"
